Add qdevice
SUSE/salt-shaptools pull request #74
Opened 2020-11-11 14:52 UTC by aleksei-burlakov

@arbulu89 @MalloZup @Simranpal  Please have a look. This PR should come together with #XXX

2020-11-12 10:13 UTC, MalloZup requested changes
thx for pr ! 3 things:

1) CODE: the code itself need adaption with the existing code. see inline comments

2) TEST: you need to adapt the tests mocking. see travis failures. ( you can find documentation on mocking on the readme, and looking at existing tests)

3) PKG: Releases: You need to add  a changelog entry to
https://github.com/SUSE/salt-shaptools/blob/master/salt-shaptools.changes#L2

and also increment the version number so basically a new pkg will shipped and then the PR you depend on this will also get the new pkgs of this shared lib.

here is where you need to increment: 
https://github.com/SUSE/salt-shaptools/blob/master/_service#L7

2020-11-12 10:15 UTC, MalloZup commented on salt/modules/crmshmod.py
> +    cmd = 'crm cluter init qdevice --qnetd-hostname={qnetd_hostname} -y'.format(
here use `{crm_command}`

2020-11-12 10:17 UTC, MalloZup commented on salt/modules/crmshmod.py
> +def _crm_init_qdevice(qnetd_hostname=None):
I think you need also to implement the `quite` parameter as the other functions

https://github.com/SUSE/salt-shaptools/pull/74/files#diff-4028dde1b1b110cd28ee9b7904381ce5b8f2666971150218ed60c08c0f6b7e61R431

2020-11-12 10:18 UTC, MalloZup commented on salt/modules/crmshmod.py
> +    cmd = 'crm cluter init qdevice --qnetd-hostname={qnetd_hostname} -y'.format(
https://github.com/SUSE/salt-shaptools/pull/74/files#diff-4028dde1b1b110cd28ee9b7904381ce5b8f2666971150218ed60c08c0f6b7e61R435

2020-11-12 17:32 UTC, Simranpal requested changes
@aleksei-burlakov some comments below

2020-11-12 17:32 UTC, Simranpal commented on salt/modules/crmshmod.py
> +def _crm_init_qdevice(qnetd_hostname=None):
The function parameters are missing in the docstring for this function

2020-11-12 17:32 UTC, Simranpal commented on salt/states/crmshmod.py
> +        create the qdevice if defined
I would add some more description about the hostname, and thats its needed to setup the QDevice

2020-11-12 17:32 UTC, Simranpal commented on salt/modules/crmshmod.py
> +    cmd = 'crm cluter init qdevice --qnetd-hostname={qnetd_hostname} -y'.format(
typo `cluter/cluster`

2020-11-13 08:05 UTC, arbulu89 reviewed
@aleksei-burlakov As a side note, I think that we can initialize qdevice in the same command where we start the cluster. This could spare this new command, and we would only need to add the flags in the current code. Just as an additional option.

Please, add the args description in the docstrings too

2020-11-13 09:25 UTC, aleksei-burlakov commented
> @aleksei-burlakov As a side note, I think that we can initialize qdevice in the same command where we start the cluster. This could spare this new command, and we would only need to add the flags in the current code. Just as an additional option.
> 
> Please, add the args description in the docstrings too

Sure. First I wanted to do it like this but then found so many functions, that I decided that this is the style to put it all in a separate function.

2020-12-09 08:09 UTC, arbulu89 requested changes
@aleksei-burlakov Added some comments.

After dealing with them, we will need to add/update the UT

2020-12-09 08:09 UTC, arbulu89 commented on salt/modules/crmshmod.py
> +    LOGGER.warning('The parameter name is not considered!')
Does this have any relationship with `qdevice`?
It doesn't look like.
I would split this into other PR. Or at least other commit, as they are unrelated

2020-12-09 08:09 UTC, arbulu89 commented on salt/modules/crmshmod.py
> +        quiet=None,
I would put `quiet` as last parameter. It looks secondary.
Usually, any user that wants to use this method only would put the `qnetid_hostname` parameter only, so being the first makes sense

2020-12-09 08:09 UTC, arbulu89 commented on salt/modules/crmshmod.py
> +    if qnetd_hostname:
Does it make any sense to run this 2nd operation if the `crm_init` failed?
Maybe, we just need to finish the process if that 1st one fails.
Something like `if not return_code and qnetd_hostname:`

2020-12-14 09:24 UTC, aleksei-burlakov commented on salt/modules/crmshmod.py
> +def _crm_init_qdevice(qnetd_hostname=None):
Done.

2020-12-14 09:24 UTC, aleksei-burlakov commented on salt/modules/crmshmod.py
> +def _crm_init_qdevice(qnetd_hostname=None):
Done.

2020-12-14 09:24 UTC, aleksei-burlakov commented on salt/states/crmshmod.py
> +        create the qdevice if defined
Done.

2020-12-14 09:25 UTC, aleksei-burlakov commented
> @aleksei-burlakov As a side note, I think that we can initialize qdevice in the same command where we start the cluster. This could spare this new command, and we would only need to add the flags in the current code. Just as an additional option.
> 
> Please, add the args description in the docstrings too

Done.

2020-12-14 09:27 UTC, aleksei-burlakov commented
> thx for pr ! 3 things:
> 
> 1. CODE: the code itself need adaption with the existing code. see inline comments
> 2. TEST: you need to adapt the tests mocking. see travis failures. ( you can find documentation on mocking on the readme, and looking at existing tests)
> 3. PKG: Releases: You need to add  a changelog entry to
>    https://github.com/SUSE/salt-shaptools/blob/master/salt-shaptools.changes#L2
> 
> and also increment the version number so basically a new pkg will shipped and then the PR you depend on this will also get the new pkgs of this shared lib.
> 
> here is where you need to increment:
> https://github.com/SUSE/salt-shaptools/blob/master/_service#L7

I have refactored the 1. CODE. No, only left are the 2. TEST and 3. Changelog

2020-12-14 14:11 UTC, aleksei-burlakov commented on salt/modules/crmshmod.py
> +    LOGGER.warning('The parameter name is not considered!')
Done.

2020-12-14 14:12 UTC, aleksei-burlakov commented on salt/modules/crmshmod.py
> +        quiet=None,
Done.

2020-12-14 14:12 UTC, aleksei-burlakov commented on salt/modules/crmshmod.py
> +    if qnetd_hostname:
It's a single command now.

2020-12-15 07:50 UTC, arbulu89 commented on salt/modules/crmshmod.py
> +    if qnetd_hostname:
@aleksei-burlakov Remember that this has the inconvenience that if the cluster is already running, it won't add the `qdevice` part there. We need to have this tracked down somewhere, as it's important to keep the state as most idempotent as possible.
Scenarios:
- Cluster is not initialized. This will create the cluster and add qdevice
- Cluster is initialized with qdevice. Most probably nothing is changed
- Cluster is initialized **without qdevice**. Nothing is changed, and this is wrong, as I would expect that `qdevice` is added

2020-12-15 14:59 UTC, aleksei-burlakov commented
I have also added the tests.

2020-12-15 16:31 UTC, aleksei-burlakov commented on salt/modules/crmshmod.py
> +    if qnetd_hostname:
> @aleksei-burlakov Remember that this has the inconvenience that if the cluster is already running, it won't add the `qdevice` part there. We need to have this tracked down somewhere, as it's important to keep the state as most idempotent as possible.
> Scenarios:
> 
> * Cluster is not initialized. This will create the cluster and add qdevice
> * Cluster is initialized with qdevice. Most probably nothing is changed
> * Cluster is initialized **without qdevice**. Nothing is changed, and this is wrong, as I would expect that `qdevice` is added

This one is outdated. The cluster is initialized in one-shot now. $ crm cluster init -s /dev/sbd ... --qnetd-hostname -y

2020-12-15 16:35 UTC, aleksei-burlakov commented on salt/modules/crmshmod.py
> +    if qnetd_hostname:
It makes sense.

2020-12-15 22:33 UTC, aleksei-burlakov commented on salt/modules/crmshmod.py
> +    if qnetd_hostname:
I see the sbd device and other parameters are also not altered on an existing running cluster when we try to initialize a new one. If we want to do this, it will require changing the old code, so I propose to split it into another PR. What do you think @arbulu89, @MalloZup, @stefanotorresi ?
I will create an issue in the meanwhile.

2020-12-15 22:55 UTC, aleksei-burlakov commented on salt/modules/crmshmod.py
> +    if qnetd_hostname:
I've created one there https://github.com/SUSE/salt-shaptools/issues/76

2020-12-16 07:54 UTC, arbulu89 commented on salt/modules/crmshmod.py
> +    if qnetd_hostname:
Ok, fair point. If we track this somewhere else we can split in a future implementation.
Could you paste the comments I did in that new ticket?

2020-12-16 07:57 UTC, arbulu89 approved these changes
@aleksei-burlakov The changes and the tests look good.
Add a changelog entry with `osc vc` explaining `qdevice` is supported now, and we are ready to go.
I'm approving the PR to avoid more reviews, but take care of the changes file first please.

2020-12-16 09:11 UTC, aleksei-burlakov commented
@MalloZup , @Simranpal please review the last changes.

2020-12-16 13:14 UTC, arbulu89 commented on salt-shaptools.changes
> +- Version 0.3.12
@aleksei-burlakov Please, remove the new version information.
Add just the next text.
We will add the version when we want to release a new package, most probably with more changes. (Like the one coming in https://github.com/SUSE/salt-shaptools/pull/77 and others).

2020-12-16 18:52 UTC, Simranpal approved these changes
thanks for the changes @aleksei-burlakov It looks good now

2021-01-18 12:48 UTC, aleksei-burlakov commented on salt-shaptools.changes
> +- Version 0.3.12
@arbulu89 I just followed the https://github.com/SUSE/salt-shaptools/pull/74#pullrequestreview-528936398. I will remove the version change.

2021-01-18 14:53 UTC, aleksei-burlakov commented on salt-shaptools.changes
> +- Version 0.3.12
@arbulu89 the version bump is reverted.

2021-01-18 15:17 UTC, merged