add module to query remote HANA
SUSE/salt-shaptools pull request #84
Opened 2022-01-21 13:03 UTC by yeoldegrove

This adds a module to query a remote HANA DB.  This let's us interact with the HANA from e.g. a S/4HANA PAS server.

It adds countless new possibilities.
- execute backups on a remote HANA--> https://github.com/SUSE/ha-sap-terraform-deployments/issues/803
- setting (persistent) DB settings remotely
- query HANA status or information remotely

2022-01-21 13:33 UTC, arbulu89 requested changes
Hey @yeoldegrove ,
The idea looks good. I have added some comments.
Besides this, we should add a new UT as it looks pretty simple to do.

2022-01-21 13:33 UTC, arbulu89 commented on salt/modules/hanamod.py
> +        user,
One potential improvement would be to give the option to use a stored key instead of the user/password.
But i'm nos sure if this works in pyhdb (in hdbapi certainly works).
Something like this: https://github.com/SUSE/salt-shaptools/blob/79f35d32a9135f956e2c29b886bb57c8ca7470cc/salt/modules/hanamod.py#L678

2022-01-21 13:33 UTC, arbulu89 commented on salt/modules/hanamod.py
> +        user,
Indeed, it only works in `hdbapi`. But it would still be insteresting.
The parameter name is `userkey`. Something like `connect(host, post, userkey=userkey, user=user, password=password)`

2022-01-21 13:33 UTC, arbulu89 commented on salt/modules/hanamod.py
> +        return result
I don't know if you will be able to use the return if you run the module directly in salt. I don't think that's possible.
Usually, this return value would be used in a python implemented salt state

2022-01-21 13:33 UTC, arbulu89 commented on salt/modules/hanamod.py
> +        result = '\n'.join([str(row) for row in rows.records])
This formatting looks pretty suboptimal. Why not return the result at all and the user can use it openly?

2022-01-21 13:33 UTC, arbulu89 commented on salt/modules/hanamod.py
> +        rows = connector.query(query)
I would call to this `result`

2022-01-24 09:39 UTC, yeoldegrove commented on salt/modules/hanamod.py
> +        user,
This would be a completely new feature as the connectors would need to be touched. I opened #85 for this.

2022-01-24 09:39 UTC, yeoldegrove commented on salt/modules/hanamod.py
> +        result = '\n'.join([str(row) for row in rows.records])
You mean getting rid of the `return` completely? Mhm...it seems odd to me to not see the output at all.
Can you elaborate on how this is "better"?

2022-01-25 10:03 UTC, arbulu89 commented on salt/modules/hanamod.py
> +        result = '\n'.join([str(row) for row in rows.records])
What is this `result` used for? It cannot be used in `salt` directly, as we cannot capture the return, and it is not used anywhere else.
If it's only for logging purpose, just log it.

2022-01-25 10:05 UTC, arbulu89 commented on salt/modules/hanamod.py
> +        rows = connector.query(query)
You didn't actually do the change here

2022-01-25 10:06 UTC, arbulu89 requested changes
@yeoldegrove 
I still see things that should be improved.
- Add some UT
- I don't still like to return a string, only for logging purposes. If we want to log the output, let's do it with good logging code. The code should return the result as it is, so the consumer can use them, and not have a string that is not usable at all

2022-01-31 16:49 UTC, yeoldegrove commented
@arbulu89 
- UTs are added
- You are right about the return values, we do not need them. They are already logged inside `INFO` e.g.:
```
[INFO    ] executing sql query: SELECT * FROM SCHEMAS
[INFO    ] query records: [('HANA_XS_BASE', '_SYS_REPO', 'TRUE', datetime.datetime(2022, 1, 19, 7, 52, 40, 623000)), ...
```

2022-02-01 07:50 UTC, arbulu89 approved these changes
Thanks @yeoldegrove ,
Fix the typo and green light

2022-02-01 07:50 UTC, arbulu89 commented on README.md
> +A list of dependencies is named avobe in the `pip install ...` commands.
Typo `avobe -> above`

2022-02-01 11:53 UTC, yeoldegrove commented on README.md
> +A list of dependencies is named avobe in the `pip install ...` commands.
:+1:

2022-02-01 12:10 UTC, yeoldegrove commented
@arbulu89 typo is fixed. Please merge.

2022-02-01 16:26 UTC, arbulu89 approved these changes
Thanks!

2022-02-01 16:26 UTC, merged